{
  "swagger": "2.0",
  "info": {
    "title": "faceit",
    "description": "faceit is small microservice to manage Users.",
    "version": "1.0"
  },
  "tags": [
    {
      "name": "FaceitService"
    }
  ],
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/v1/users": {
      "get": {
        "summary": "ListUsersByCountry list users by country.",
        "description": "Receives a request with country data. Responses a list of users.",
        "operationId": "FaceitService_ListUsersByCountry",
        "responses": {
          "200": {
            "description": "List of users by country paginated.",
            "schema": {
              "$ref": "#/definitions/faceitUserList"
            }
          },
          "400": {
            "description": "Bad Request.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 400,
                "message": "Bad Request",
                "error": "Invalid argument",
                "details": [
                  {
                    "field": "field",
                    "description": "invalid"
                  }
                ]
              }
            }
          },
          "500": {
            "description": "Internal error.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 500,
                "message": "message",
                "error": "error_id_uuid"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "country",
            "description": "Country of the user.",
            "in": "query",
            "required": true,
            "type": "string"
          },
          {
            "name": "pageSize",
            "description": "The maximum number of user to return. The service may return fewer than\nthis value.\nIf unspecified, at most 100 users will be returned.\nThe maximum value is 1000; values above 1000 will be coerced to 1000.",
            "in": "query",
            "required": false,
            "type": "integer",
            "format": "int32"
          },
          {
            "name": "pageToken",
            "description": "A page token, received from a previous `UserList` call.\nProvide this to retrieve the subsequent page.\n\nWhen paginating, all other parameters provided to `UserList` must match\nthe call that provided the page token.",
            "in": "query",
            "required": false,
            "type": "string"
          }
        ],
        "tags": [
          "FaceitService"
        ]
      },
      "post": {
        "summary": "AddUser add new user.",
        "description": "Receives a request with user data. Responses whether the user was added successfully or not.",
        "operationId": "FaceitService_AddUser",
        "responses": {
          "204": {
            "description": "User was added successfully.",
            "schema": {
              "$ref": "#/definitions/protobufEmpty"
            },
            "examples": {
              "application/json": {}
            }
          },
          "400": {
            "description": "Bad Request.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 400,
                "message": "Bad Request",
                "error": "Invalid argument",
                "details": [
                  {
                    "field": "field",
                    "description": "invalid"
                  }
                ]
              }
            }
          },
          "500": {
            "description": "Internal error.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 500,
                "message": "message",
                "error": "error_id_uuid"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "body",
            "description": "Message represents user.",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/faceitUser"
            }
          }
        ],
        "tags": [
          "FaceitService"
        ]
      }
    },
    "/v1/users/{id}": {
      "delete": {
        "summary": "Delete the user.",
        "description": "Receives a request with user data id. Responses whether the user was deleted successfully or not.",
        "operationId": "FaceitService_DeleteUser",
        "responses": {
          "204": {
            "description": "User was deleted successfully.",
            "schema": {
              "$ref": "#/definitions/protobufEmpty"
            }
          },
          "400": {
            "description": "Bad Request.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 400,
                "message": "Bad Request",
                "error": "Invalid argument",
                "details": [
                  {
                    "field": "field",
                    "description": "invalid"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "User not found.",
            "schema": {
              "$ref": "#/definitions/protobufEmpty"
            }
          },
          "500": {
            "description": "Internal error.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 500,
                "message": "message",
                "error": "error_id_uuid"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "description": "ID of the user.",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "tags": [
          "FaceitService"
        ]
      },
      "patch": {
        "summary": "Update the user.",
        "description": "Receives a request with user data. Responses whether the user was updated successfully or not.",
        "operationId": "FaceitService_UpdateUser",
        "responses": {
          "204": {
            "description": "User was updated successfully.",
            "schema": {
              "$ref": "#/definitions/protobufEmpty"
            }
          },
          "400": {
            "description": "Bad Request.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 400,
                "message": "Bad Request",
                "error": "Invalid argument",
                "details": [
                  {
                    "field": "field",
                    "description": "invalid"
                  }
                ]
              }
            }
          },
          "404": {
            "description": "User not found.",
            "schema": {
              "$ref": "#/definitions/protobufEmpty"
            }
          },
          "500": {
            "description": "Internal error.",
            "schema": {
              "$ref": "#/definitions/rpcStatus"
            },
            "examples": {
              "application/json": {
                "code": 500,
                "message": "message",
                "error": "error_id_uuid"
              }
            }
          }
        },
        "parameters": [
          {
            "name": "id",
            "description": "ID of the user.",
            "in": "path",
            "required": true,
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/FaceitServiceUpdateUserBody"
            }
          }
        ],
        "tags": [
          "FaceitService"
        ]
      }
    }
  },
  "definitions": {
    "FaceitServiceUpdateUserBody": {
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string",
          "description": "First name of the user."
        },
        "lastName": {
          "type": "string",
          "description": "Last name of the user."
        },
        "nickname": {
          "type": "string",
          "description": "Nickname of the user."
        },
        "passwordHash": {
          "type": "string",
          "description": "Password hash of the user."
        },
        "email": {
          "type": "string",
          "description": "Email of the user."
        },
        "country": {
          "type": "string",
          "description": "Country of the user."
        }
      },
      "description": "Message represents user.",
      "title": "User"
    },
    "faceitUser": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string",
          "description": "ID of the user."
        },
        "firstName": {
          "type": "string",
          "description": "First name of the user."
        },
        "lastName": {
          "type": "string",
          "description": "Last name of the user."
        },
        "nickname": {
          "type": "string",
          "description": "Nickname of the user."
        },
        "passwordHash": {
          "type": "string",
          "description": "Password hash of the user."
        },
        "email": {
          "type": "string",
          "description": "Email of the user."
        },
        "country": {
          "type": "string",
          "description": "Country of the user."
        }
      },
      "description": "Message represents user.",
      "title": "User",
      "required": [
        "id"
      ]
    },
    "faceitUserList": {
      "type": "object",
      "properties": {
        "users": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/faceitUser"
          },
          "description": "List of users."
        },
        "nextPageToken": {
          "type": "string",
          "description": "A token that can be sent as `page_token` to retrieve the next page.\nIf this field is omitted, there are no subsequent pages."
        }
      },
      "description": "Response message represent list of users.",
      "title": "UserListResponse"
    },
    "protobufAny": {
      "type": "object",
      "properties": {
        "@type": {
          "type": "string"
        }
      },
      "additionalProperties": {}
    },
    "protobufEmpty": {
      "type": "object",
      "description": "service Foo {\n      rpc Bar(google.protobuf.Empty) returns (google.protobuf.Empty);\n    }",
      "title": "A generic empty message that you can re-use to avoid defining duplicated\nempty messages in your APIs. A typical example is to use it as the request\nor the response type of an API method. For instance:"
    },
    "rpcStatus": {
      "type": "object",
      "properties": {
        "code": {
          "type": "integer",
          "format": "int32"
        },
        "message": {
          "type": "string"
        },
        "details": {
          "type": "array",
          "items": {
            "type": "object",
            "$ref": "#/definitions/protobufAny"
          }
        }
      }
    }
  }
}
